### ISSUE TITLE
Project Update

### ISSUE THREAD

**Issue by boilermanc** [smar000/openhab-ai#1]
Hi! Very interested in what you have started. I am going to try to implement it on the greenhouse management app that I built in openhab. I have some questions though.

I understand the cfg file. You have a couple of other files like logger. Where do they go? 

You talk about having it output as REST to Openhab. I know how to load the REST binding but not sure what/how my output should be configured? 

When you create the new item, what does that item look like? How would you use it? 

I will try to match one of my use cases against what you have in the sample and see if I can ask a more specific questions.

This is great stuff and pretty amazing if I can get it going to do some of the things I want to do with the greenhouse data.

thanks!
Clint

**Comment by smar000** [comment]
Hi

> You have a couple of other files like logger. Where do they go?
> 
Everything goes into the same folder as the script.


> You talk about having it output as REST to Openhab. I know how to load the REST binding but not sure what/how my output should be configured?

There is no REST binding required as such. REST is built in into openHAB and is just a way for the script to communicate directly with openHAB. Not sure what you mean by configuring your "output". All you need to do is define your openHAB url correctly in the config file.

> 
> When you create the new item, what does that item look like? How would you use it?
> 

Again, I am not sure what you mean here. Items are just normal openHAB items. I only used Switch items when I put together the script, as I was only interested in ON/OFF predictions.

**Comment by boilermanc** [comment]
Thanks so much for getting back to me. Was thinking about this this morning. Appreciate the information. Will dig in and see what we can do. I want to use it in the greenhouse for predicting around several use cases. 

Where do the following files go? 

.gitignore
openhab_ai.py
rule_model.py
sse.py

thanks!

**Comment by smar000** [comment]
They can go in any folder you like. They have nothing to do with openHAB directly, and are just standard python scripts.
